export const FFmpegColor = [
   'AliceBlue',
   'AntiqueWhite',
   'Aqua',
   'Aquamarine',
   'Azure',
   'Beige',
   'Bisque',
   'Black',
   'BlanchedAlmond',
   'Blue',
   'BlueViolet',
   'Brown',
   'BurlyWood',
   'CadetBlue',
   'Chartreuse',
   'Chocolate',
   'Coral',
   'CornflowerBlue',
   'Cornsilk',
   'Crimson',
   'Cyan',
   'DarkBlue',
   'DarkCyan',
   'DarkGoldenRod',
   'DarkGray',
   'DarkGreen',
   'DarkKhaki',
   'DarkMagenta',
   'DarkOliveGreen',
   'Darkorange',
   'DarkOrchid',
   'DarkRed',
   'DarkSalmon',
   'DarkSeaGreen',
   'DarkSlateBlue',
   'DarkSlateGray',
   'DarkTurquoise',
   'DarkViolet',
   'DeepPink',
   'DeepSkyBlue',
   'DimGray',
   'DodgerBlue',
   'FireBrick',
   'FloralWhite',
   'ForestGreen',
   'Fuchsia',
   'Gainsboro',
   'GhostWhite',
   'Gold',
   'GoldenRod',
   'Gray',
   'Green',
   'GreenYellow',
   'HoneyDew',
   'HotPink',
   'IndianRed',
   'Indigo',
   'Ivory',
   'Khaki',
   'Lavender',
   'LavenderBlush',
   'LawnGreen',
   'LemonChiffon',
   'LightBlue',
   'LightCoral',
   'LightCyan',
   'LightGoldenRodYellow',
   'LightGreen',
   'LightGrey',
   'LightPink',
   'LightSalmon',
   'LightSeaGreen',
   'LightSkyBlue',
   'LightSlateGray',
   'LightSteelBlue',
   'LightYellow',
   'Lime',
   'LimeGreen',
   'Linen',
   'Magenta',
   'Maroon',
   'MediumAquaMarine',
   'MediumBlue',
   'MediumOrchid',
   'MediumPurple',
   'MediumSeaGreen',
   'MediumSlateBlue',
   'MediumSpringGreen',
   'MediumTurquoise',
   'MediumVioletRed',
   'MidnightBlue',
   'MintCream',
   'MistyRose',
   'Moccasin',
   'NavajoWhite',
   'Navy',
   'OldLace',
   'Olive',
   'OliveDrab',
   'Orange',
   'OrangeRed',
   'Orchid',
   'PaleGoldenRod',
   'PaleGreen',
   'PaleTurquoise',
   'PaleVioletRed',
   'PapayaWhip',
   'PeachPuff',
   'Peru',
   'Pink',
   'Plum',
   'PowderBlue',
   'Purple',
   'Red',
   'RosyBrown',
   'RoyalBlue',
   'SaddleBrown',
   'Salmon',
   'SandyBrown',
   'SeaGreen',
   'SeaShell',
   'Sienna',
   'Silver',
   'SkyBlue',
   'SlateBlue',
   'SlateGray',
   'Snow',
   'SpringGreen',
   'SteelBlue',
   'Tan',
   'Teal',
   'Thistle',
   'Tomato',
   'Turquoise',
   'Violet',
   'Wheat',
   'White',
   'WhiteSmoke',
   'Yellow',
   'YellowGreen',
] as const;

export const Curves = [
   'tri',
   'qsin',
   'hsin',
   'esin',
   'log',
   'ipar',
   'qua',
   'cub',
   'squ',
   'cbr',
   'par',
   'exp',
   'iqsin',
   'ihsin',
   'dese',
   'desi',
   'losi',
   'sinc',
   'isinc',
   'quat',
   'quatr',
   'qsin2',
   'hsin2',
   'nofade',
] as const;

export const ColorPresets = [
   'sepia',
   'golden hour',
   'purple noir',
   'grayscale',
   'moonlight',
   'teal & orange',
   'vibrant',
   'desaturated',
   'negative',
   'matrix code green',
   'cyberpunk',
] as const;

export const AspectRatios = [
   '1:1',
   '1:2',
   '2:1',
   '2:3',
   '3:2',
   '3:4',
   '4:3',
   '4:5',
   '5:4',
   '9:16',
   '9:21',
   '9:32',
   '10:16',
   '16:9',
   '16:10',
   '21:9',
   '32:9',
] as const;

export const ScaleFlags = ['bilinear', 'bicubic', 'lanczos', 'gaussian'];

export const TextAlign = [
   'left+top',
   'left+middle',
   'left+bottom',
   'center+top',
   'center+middle',
   'center+bottom',
   'right+top',
   'right+middle',
   'right+bottom',
] as const;

export const VideoSize = [
   // SD
   '640x480',
   '480x640',

   // DVD
   '720x480',
   '480x720',
   '720x576',
   '576x720',

   // HD
   '1280x720',
   '720x1280',

   // Full HD
   '1920x1080',
   '1080x1920',

   // QHD
   '2560x1440',
   '1440x2560',

   // 4K UHD
   '3840x2160',
   '2160x3840',

   // 4K DCI (cine)
   '4096x2160',
   '2160x4096',

   // 8K UHD
   '7680x4320',
   '4320x7680',

   // Legacy
   '854x480',
   '480x854',
   '960x540',
   '540x960',
   '1024x768',
   '768x1024',
   '1366x768',
   '768x1366',
   '320x240',
   '240x320',
   '640x360',
   '360x640',

   // Social Media
   '1080x1080',
   '1080x1350',
   '1350x1080',
] as const;
