export const FFmpegColor = [
   'black@0',
   'black@1',
   'white@1',
   'red@1',
   'green@1',
   'blue@1',
   'yellow@1',
   'cyan@1',
   'magenta@1',
   'gray@1',
   'darkblue@1',
   'darkred@1',
   'darkgreen@1',
   'darkgray@1',
   'lightblue@1',
   'lightred@1',
   'lightgreen@1',
   'lightgray@1',
] as const;
